id: P010537
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:54:51.483249
source_metadata:
  id: bdr:W20138
  title: བོད་རིག་པའི་དཔྱད་གླེང་གྲོག་ཆུ་ཕྲ་མོའི་སྟངས་སྟབས
  author: ''
  volumes:
    dab64977809e42569e05044bf264f50c:
      image_group_id: I4237
      title: ''
      volume_number: 1
      total_pages: 476
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
